trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: BuildFrontend
    displayName: 'Build Frontend'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        cd front
        npm install
        npm run build
      displayName: 'Build Frontend'
  
  - job: BuildBackend
    displayName: 'Build Backend'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        cd back
        npm install
        npm test
      displayName: 'Build and Test Backend'

